#!/usr/bin/env bash

PINK='\033[95m'
OKBLUE='\033[94m'
WARNING='\033[93m'
ERROR='\033[91m'
OKGREEN='\033[92m'
ENDC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'

while read line ; do
  if [[ $line == *"[ERROR]"* ]]; then
    color=$ERROR
  elif [[ $line == *"[WARNING]"* ]]; then
    color=$WARNING
  elif [[ $line == *"[INFO]"* ]]; then
    color=$OKBLUE
  else
    color=$PINK
  fi

  echo -e "$color $line $ENDC"

done
